repository:
  has_wiki: false
  has_projects: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
