version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: ${DOCKER_TARGET_APP:-fpm}
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        working_dir: /var/www
        environment:
            - DOCKER=1
            - PHP_IDE_CONFIG=serverName=slim.local
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
            - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www
        ports:
            - ${EXTERNAL_APP_PORT:-80}:8080
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - slim

    db:
        image: postgres:17.4
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            PGPASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data
        networks:
            - slim

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.1.0-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-rabbitmq}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-app}
        networks:
            - slim

    redis:
        image: redis:7.4.3-alpine3.21
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-6379}:6379
        networks:
            - slim
        restart: unless-stopped

networks:
    slim:
        driver: bridge
