version: '3'
services:
    web:
        image: nginx
        volumes:
            - .docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www:delegated
        ports:
            - ${EXTERNAL_WEB_PORT:-80}:80
        networks:
            - slim
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile-dev
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        working_dir: /var/www
        environment:
            - DOCKER=1
            - PHP_IDE_CONFIG=serverName=slim.local
        volumes:
            - .docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
 #           - .docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www:delegated
        ports:
            - ${EXTERNAL_PHP_PORT:-9000}:9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - slim
    db:
        image: postgres:13
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            PGPASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data
        networks:
            - slim
# Networks
networks:
    slim:
        driver: bridge
