version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: .docker/dev/php/Dockerfile
            args:
                INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
        working_dir: /var/www
        environment:
            - DOCKER=1
            - PHP_IDE_CONFIG=serverName=slim.local
        volumes:
            - ./.docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/dev/php/php-fpm.conf:/etc/php/fpm/php-fpm.conf
            - .:/var/www
        ports:
            - ${EXTERNAL_APP_PORT:-80}:80
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - slim
    db:
        image: postgres:16
        ports:
            - ${FORWARD_DB_PORT:-5432}:5432
        environment:
            PGPASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /var/lib/postgresql/data
        networks:
            - slim
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-rabbitmq}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-app}
        networks:
            - slim
    redis:
        image: redis:7.0.11-alpine3.17
        ports:
            - ${DOCKER_REDIS_HOST_PORT:-6379}:6379
        networks:
            - slim
        restart: unless-stopped
# Networks
networks:
    slim:
        driver: bridge
