apiVersion: v1
kind: Service
metadata:
  name: {{ include "slim4-app.fullname" . }}
  labels:
    {{- include "slim4-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    {{- include "slim4-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
