name: Test&lint PHP codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint-php:
    name: Test&lint PHP codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    services:
      pgsql:
        image: postgres:17.11-alpine3.24@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73
        env:
          POSTGRES_DB: slim
          POSTGRES_USER: slim
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 3s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1 # https://github.com/actions/checkout

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0 # https://github.com/actions/cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-dependencies-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-dependencies

      - name: Cache isolated dev tools
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0 # https://github.com/actions/cache
        with:
          path: tools/*/vendor
          key: ${{ runner.os }}-composer-tools-${{ hashFiles('tools/*/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-tools

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2 # https://github.com/shivammathur/setup-php
        with:
          php-version: 8.5
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, intl, sockets, rdkafka-6.0.5
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --classmap-authoritative --prefer-dist --no-interaction

      - name: Install isolated dev tools
        run: composer tools:install

      - name: Run PHP linter
        run: composer cs:check

      - name: Run PHPSTAN
        run: composer phpstan

      - name: Execute Architecture tests
        run: |
          composer test:architecture
          
      - name: Execute tests
        run: |
          cp .env.test .env
          composer migrate
          php -dopcache.validate_timestamps=0 vendor/bin/phpunit --testsuite "Test Suite" --log-junit junit.xml --coverage-clover clover.xml

      - name: Send test coverage to codecov.io
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0 # https://github.com/codecov/codecov-action
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: clover.xml
          fail_ci_if_error: true
          verbose: true